#!/bin/sh 

# 64 BIT!!!

# SIMPLE SCRIPT WHICH CREATES A DESKTOP SHORTCUT TO B-Step IN THIS FOLDER

# 1. GET CURRENT LOCATION
current_folder=`pwd`

# 2. GENERATE SHORTCUT
touch $HOME/Desktop/Monique.desktop
echo "[Desktop Entry]
GenericName=Monique
Encoding=UTF-8
Comment=Monophonic Unique Synthesizer
Type=Application
Categories=AudioVideo;Audio;
Terminal=false
StartupNotify=false
Name=Monique
Terminal=false
Version=0.9.9.7
Path=$current_folder
Exec=$current_folder/Monique
Icon=$current_folder/Monique.png" > $HOME/Desktop/Monique.desktop

# MAKE SURE Monique IS EXECUTABLE
chmod +x "$current_folder/Monique"