name: Build Pull Request
on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build_plugin:
    name: PR - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
          - os: macos-latest
          - os: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare for JUCE
        uses: surge-synthesizer/sst-githubactions/prepare-for-juce@main
        with:
          os: ${{ runner.os }}

      - name: Build pull request version
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Debug 
          cmake --build ./build --config Debug --target monique-staged --parallel 3

  build_plugin_lindoc:
    name: PR - U18 Docker
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/surge-synthesizer/sst-dockerimages/ubuntu18_gcc11:main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build pull request version
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Debug 
          cmake --build ./build --config Debug --target monique-staged --parallel 3
