on:
  workflow_call:

jobs:
  prepare_system:
    steps:
      - name: Select Xcode Version
        if: runner.os == 'macOS'
        run: sudo xcode-select -switch /Applications/Xcode_15.1.app

      - name: Install Linux Deps; pick GCC12
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt install libasound2-dev libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libfreetype6-dev libglu1-mesa-dev libjack-jackd2-dev
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12

